apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  # NodePort LoadBalancer ClusterIP
  type: LoadBalancer
  ports:
      - port: 31889
        targetPort: 8080
  selector:
    app: backend-app
